### ISSUE TITLE
Zcrypto refuses to comile with go 1.10rc1 on macos

### ISSUE THREAD

**Issue by szank** [zmap/zcrypto#106]
Hi, I have been testing the go@1.10rc and discovered that this package doesn't compile: 
I am getting:
`vendor/github.com/zmap/zcrypto/ct/x509/root_darwin.go:73: cannot use nil as type _Ctype_CFDataRef in assignment`

After a quick glance I have discovered that zcrypto/ct/x509 is quite outdated compared to the https://github.com/google/certificate-transparency-go and the baseline x509 package. The same thing for zcrypto/ct/asn1 and possibly zcrypto/x509. 

Updating the offending functions should be easy enough,  and I could do that, but I tried to merge github.com/google/certificate-transparency-go into zcrypto and it turned out bit tricky. 
There are small changes sprinkled here and there, and without knowing what and where have been modified it is very easy to miss something. And not all is wrapped in `// Begin CT changes`, `// End CT changes`. 

I can open a PR to just update the offending parts, so there is no nasty surprise when other users of this repo jump to go 1.10, but I'd suggest an general update to the x509/asn1 packages.

**Comment by adamdecaf** [comment]
I was able to get around with this smaller fix. PR'ing as I wasn't able to find your change specific to those couple of errors. (Rather than updating the x509 forks) 

https://github.com/zmap/zcrypto/pull/109

**Comment by szank** [comment]
This is solved no. Zcrypto works on go1.10 and previous versions.
