### ISSUE TITLE
ct/x509: Package fails to build on Darwin with Go 1.10.1

### ISSUE THREAD

**Issue by leonklingele** [zmap/zcrypto#121]
`zgrab` fails to build on OS X running Go 1.10.1:

```sh
$ go get -u github.com/zmap/zgrab
# github.com/zmap/zgrab/vendor/github.com/zmap/zcrypto/ct/x509
vendor/github.com/zmap/zcrypto/ct/x509/root_darwin.go:73: cannot use nil as type _Ctype_CFDataRef in assignment
```

Related: https://github.com/google/certificate-transparency-go/issues/131
Fix seems to be in https://github.com/google/certificate-transparency-go/pull/155

**Comment by leonklingele** [comment]
As a workaround, build with Go 1.9:

```
$ brew install go@1.9
$ /usr/local/opt/go@1.9/bin/go get -u github.com/zmap/zgrab
```

**Comment by andrewvc** [comment]
The fix in https://github.com/google/certificate-transparency-go/pull/155 seems to be merged , would it be possible to fix it in zcrypto?
