### ISSUE TITLE
Dependency github.com/zmap/rc2 has no license

### ISSUE THREAD

**Issue by eclipseo** [zmap/zcrypto#201]
I'm trying to package github.com/zmap/zcrypto for my distribution, but the dependency github.com/zmap/rc2 has no license and no way to file an issue. Could you please specify under what license is the code distributed?
Thanks.

**Comment by eclipseo** [comment]
Upstream chose Apache 2.0, it would be great if you could include the LICENSE file in the fork: https://github.com/tqbf/rc2/blob/master/LICENSE

**Comment by dadrian** [comment]
The `LICENSE` is currently in master.
