### ISSUE TITLE
Google CRLSet fetch broken

### ISSUE THREAD

**Issue by cpu** [zmap/zcrypto#203]
:wave: It looks like the `TestFetch` unit test from the `x509/revocation/google` package is consistently failing.  I bumped into this with https://github.com/zmap/zcrypto/pull/202 but it reproduces with Go 1.12.x and seems unrelated. 

I'm not familiar with CRLSet implementation details or Chrome internals but it looks to me like the upstream API has changed and the test failure is a true positive. Here's my quick drive-by diagnosis. 

Adding some debug statements to the test shows `fetch` making a GET request to

 ```
http://clients2.google.com/service/update2/crx?x=id%3Dhfnkpimlhhgieaddgfemjhofmfblmnib%26v%3D%26uc
```
and getting back the XML response:
```
<?xml version="1.0" encoding="UTF-8"?><gupdate xmlns="http://www.google.com/update2/response" protocol="2.0" server="prod"><daystart elapsed_days="4641" elapsed_seconds="46697"/><app appid="hfnkpimlhhgieaddgfemjhofmfblmnib" cohort="1:jcl:" cohortname="Auto" status="ok"><updatecheck status="noupdate"/></app></gupdate>
```

The test is expecting `fetch` to iterate `Apps` elements in the response to pull out a `URL` and `Version` attribute from child `UpdateCheck` elements to find a usable `crxURL`. The response above doesn't include this information in the XML so ultimately `fetch` returns a `errors.New("Failed to parse Omaha response")` `err` and the `TestFetch` unit tests fails.

It seems like the code in this package is adopted from [Agl's crlset-tools](https://github.com/agl/crlset-tools) and I notice that he recently updated the library to account for a new API version: https://github.com/agl/crlset-tools/commit/eb2087904f67e44f1806ae27dcde149e908a4c91

The approach taken in the `crlset-tools` package skips signature checking. I'm not familiar enough with this part of `zcrypto` or its intended use-cases to determine if that's an appropriate trade-off for this package to adopt as well. If it is acceptable then backporting the update from `crlset-tools` will probably fix this problem.

**Comment by cpu** [comment]
> If it is acceptable then backporting the update from crlset-tools will probably fix this problem.

If not checking the signature is fine with folks I can volunteer to do the backporting. If it isn't I think it would be better to task someone with more context to do the needed update, or to consider removing the code from `zcrypto` until it can be fixed.

**Comment by zakird** [comment]
I think it's fine not to check the signature here. We're not using ZCrypto for production applications that you would mandate the check. If you're willing to backport, that would be much appreciated.

**Comment by cpu** [comment]
> If you're willing to backport, that would be much appreciated.

@zakird PTAL: https://github.com/zmap/zcrypto/pull/205
