### ISSUE TITLE
ZCrypto parsed the Netscape Comment to unknown extensions

### ISSUE THREAD

**Issue by GOODPWDCETCSZ** [zmap/zcrypto#221]
ZCrypto parsed the Netscape Comment to unknown extensions
[cert-example-ie-cer40.zip](https://github.com/zmap/zcrypto/files/4600575/cert-example-ie-cer40.zip)

**Comment by Lcys** [comment]
I ran into the same problem

**Comment by cpu** [comment]
It looks like https://github.com/zmap/zcrypto/issues/248 was filed as a duplicate of this. Since that issue has a little bit more information I'm going to close this one. Thanks!

**Comment by GOODPWDCETCSZ** [comment]
@cpu Thanks.
