### ISSUE TITLE
SCT List parsing bugs.

### ISSUE THREAD

**Issue by dandragona-dev** [zmap/zcrypto#228]
https://github.com/zmap/zcrypto/blob/2760ff0e1c2515ce20d8da0f364511ea6bb444cb/x509/x509.go#L1907

SCTLists of length 3 will cause a seg fault when we reference scts[1]. We should make the for loop check to have len(scts) > 1.

Furthermore, we should add a better check on the length defined by scts[0] and scts[1] to make sure that it is a reasonable number (0 <= length +2  <= len(scts)).

**Comment by cpu** [comment]
Thanks for the bug report. This is fixed in master as of 4bcf4a9
