### ISSUE TITLE
why handshake failure ?

### ISSUE THREAD

**Issue by chushuai** [zmap/zcrypto#229]
Can be accessed normally through the browser

https://1.179.232.207:1080

Here is the test code
```
import (
	"fmt"
	"github.com/zmap/zcrypto/tls"
	"testing"
)

func TestTLS(t *testing.T) {
	config := tls.Config{
		InsecureSkipVerify: true,
		MaxVersion:         tls.VersionTLS12,
	}
	/*
	https://1.179.232.207:1080
	*/
	conn, err := tls.Dial("tcp", "1.179.232.207:1080", &config)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(conn)
	defer conn.Close()
}

```

**Comment by mzpqnxow** [comment]
This seems to be the same as https://github.com/zmap/zgrab2/issues/281, you can read what I wrote there

I wonder if the default cipher-suite profiles need to be updated in zcrypto to be more inclusive to junk like this device (which seems to be an old NETGEAR router)

**Comment by chushuai** [comment]
I don't have this problem with the latest version of golang crypto/tls.  zcrypto's crypto/tls is too old version
@cpu @mzpqnxow

**Comment by mzpqnxow** [comment]
@chushuai are you building from source, or using a release package from somewhere?

**Comment by mzpqnxow** [comment]
@chushuai if you would like to test, I have a zcrypto branch @ https://github.com/mzpqnxow/zcrypto/tree/feature/portable-cipher-suite-profile that provides a pre-build list of cipher-suites that will address this and should handle any similar issues you run into with other endpoints that are picky. If you use that branch, you'd need to update your code to specify `CipherSuites` in the TLS config:

	`CipherSuites = tls.PortableCiphers`

I sent in a PR for this, but please feel free to test in the mean time. I also tested it with `zgrab2` and will add a branch that makes use of this once/if this is merged

**Comment by mzpqnxow** [comment]
Was this issue resolved for you @chushuai ? A lot of work has been done in zcrypto since the time you created this

**Comment by mzpqnxow** [comment]
> Was this issue resolved for you @chushuai ? A lot of work has been done in zcrypto since the time you created this

Pretty sure this is resolved and can be closed
