### ISSUE TITLE
x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by 89z** [zmap/zcrypto#317]
I cant seem to make any requests. I tried this program, and I get the above message:

~~~go
package main

import (
   "github.com/zmap/zcrypto/tls"
   "net/http"
)

func main() {
   req, err := http.NewRequest("GET", "https://www.howsmyssl.com/a/check", nil)
   if err != nil {
      panic(err)
   }
   if _, err := tls.Dial(
      "tcp", req.URL.Host + ":" + req.URL.Scheme, &tls.Config{
         ServerName: req.URL.Host,
      },
   ); err != nil {
      panic(err) // x509: failed to load system roots and no roots provided
   }
}
~~~

Another example:

~~~go
package main

import (
   "github.com/zmap/zcrypto/tls"
   "net"
   "net/http"
)

func main() {
   req, err := http.NewRequest("GET", "https://www.howsmyssl.com/a/check", nil)
   if err != nil {
      panic(err)
   }
   nConn, err := net.Dial("tcp", req.URL.Host + ":" + req.URL.Scheme)
   if err != nil {
      panic(err)
   }
   tConn := tls.Client(nConn, &tls.Config{ServerName: req.URL.Host})
   if err := req.Write(tConn); err != nil {
      panic(err) // x509: failed to load system roots and no roots provided
   }
}
~~~

**Comment by dadrian** [comment]
You need to provide an explicit root store or disable verification. ZCrypto does not automatically load roots.

**Comment by 89z** [comment]
Why does `crypto/tls` automatically load roots, but this package doesnt?

**Comment by zakird** [comment]
ZCrypto is primarily used for Internet measurement, a situation where you want such decisions to be explicit not implicit. Otherwise, the results from your measurement could vary dramatically between computers you use.

**Comment by 89z** [comment]
OK, but for users who do want the simple straight forward path, is a struct field or any option available to make this happen?

**Comment by dadrian** [comment]
Pass a root store to the `tls.Config` object. Users looking for things to work automatically really shouldn't be using this library. It's specifically _not_ designed to be secure.

**Comment by 89z** [comment]
> Pass a root store to the `tls.Config` object. Users looking for things to work automatically really shouldn't be using this library. It's specifically _not_ designed to be secure.

Please dont make assumptions about me or my use case. I am looking for a "hello world" example, which I can then change as appropriate. Right now I have nothing but panics. So any help other than "dont use this package" would be appreciated.

**Comment by zakird** [comment]
Please look at how ZGrab2 uses the library: https://github.com/zmap/zgrab2/blob/master/modules/tls.go.

**Comment by 89z** [comment]
@zakird  thank you for the link, however that file doesnt appear to make an HTTPS request, which is what I am trying to do

**Comment by 89z** [comment]
This seems to do it:

~~~go
package crypto

import (
   "bufio"
   "github.com/zmap/zcrypto/tls"
   "net/http"
)

func request(req *http.Request) (*http.Response, error) {
   config := &tls.Config{
      InsecureSkipVerify: true,
      ServerName: req.URL.Host,
   }
   conn, err := tls.Dial("tcp", req.URL.Host + ":" + req.URL.Scheme, config)
   if err != nil {
      return nil, err
   }
   if err := req.Write(conn); err != nil {
      return nil, err
   }
   return http.ReadResponse(bufio.NewReader(conn), req)
}
~~~
