### ISSUE TITLE
the cert  browser is trusted， but  zcrypto Invalid display certificate？

### ISSUE THREAD

**Issue by chushuai** [zmap/zcrypto#341]
https://new-proxy.shunwang.com/

the cert  browser is trusted， but  zcrypto Invalid display certificate

![image](https://user-images.githubusercontent.com/5875458/180752959-5216bd23-c503-40cd-8c47-0f80a6ca7d78.png)

![image](https://user-images.githubusercontent.com/5875458/180753612-0bb7f732-a6f6-47ad-9682-7673f9906856.png)

**Comment by chushuai** [comment]
does not load system default certificate	
The zcrypto code  
https://github.com/zmap/zcrypto/blob/master/x509/verify.go#L283 
 ```
	if opts.Roots == nil {
		err = SystemRootsError{}
		return
	}
```

the golang crypto/tls 
```

if opts.Roots == nil {
		opts.Roots = systemRootsPool()
		if opts.Roots == nil {
			return nil, SystemRootsError{systemRootsErr}
		}
	}
```

**Comment by mzpqnxow** [comment]
I believe this is by design, to provide flexibility

If you desire the same behavior as the upstream golang tls, you should set opt.roots = systemRootsPool() when calling that function

**Comment by dadrian** [comment]
Yes, this is intentional. You must provide your own roots when using ZCrypto.
