### ISSUE TITLE
How is the signature value encoded?

### ISSUE THREAD

**Issue by itqfnu** [zmap/zcrypto#369]
The signature value e.g., ut4t+t+vs8ibsc4zncmvk6huidj0fmbfdlm48hawqjy2rmmvhjqn6unxywn/ofpekotvqwtd6zkun1kaeg/4yql4fpvefzofgqf6yti4av5b6kp96gg60g7xsb2ojjxzdzo7c4mxa7g8yxbdmfnjj5us5i0ayj7gsbtxzwd4new= output by ZCertificate is different from that e.g., 131222815620619450152666948257059121950907829953519244539886480378470062010096647575553534612461415927807182823505688109619085255687373003099512250583765676892292109195281636457932272659794607398513664009591492341796935354091677654429662878582317202330630895009091162736437633095724131716075815149269419570668 output by OpenSSL.

The signature values output by ZCertificate looks like base64. However, the base64-encoded 131222815620619450152666948257059121950907829953519244539886480378470062010096647575553534612461415927807182823505688109619085255687373003099512250583765676892292109195281636457932272659794607398513664009591492341796935354091677654429662878582317202330630895009091162736437633095724131716075815149269419570668 is MTMxMjIyODE1NjIwNjE5NDUwMTUyNjY2OTQ4MjU3MDU5MTIxOTUwOTA3ODI5OTUzNTE5MjQ0NTM5ODg2NDgwMzc4NDcwMDYyMDEwMDk2NjQ3NTc1NTUzNTM0NjEyNDYxNDE1OTI3ODA3MTgyODIzNTA1Njg4MTA5NjE5MDg1MjU1Njg3MzczMDAzMDk5NTEyMjUwNTgzNzY1Njc2ODkyMjkyMTA5MTk1MjgxNjM2NDU3OTMyMjcyNjU5Nzk0NjA3Mzk4NTEzNjY0MDA5NTkxNDkyMzQxNzk2OTM1MzU0MDkxNjc3NjU0NDI5NjYyODc4NTgyMzE3MjAyMzMwNjMwODk1MDA5MDkxMTYyNzM2NDM3NjMzMDk1NzI0MTMxNzE2MDc1ODE1MTQ5MjY5NDE5NTcwNjY4.

I wonder how the signature value is encoded from 131222815620619450152666948257059121950907829953519244539886480378470062010096647575553534612461415927807182823505688109619085255687373003099512250583765676892292109195281636457932272659794607398513664009591492341796935354091677654429662878582317202330630895009091162736437633095724131716075815149269419570668 to ut4t+t+vs8ibsc4zncmvk6huidj0fmbfdlm48hawqjy2rmmvhjqn6unxywn/ofpekotvqwtd6zkun1kaeg/4yql4fpvefzofgqf6yti4av5b6kp96gg60g7xsb2ojjxzdzo7c4mxa7g8yxbdmfnjj5us5i0ayj7gsbtxzwd4new=. Could you explain it? TKS!

**Comment by dadrian** [comment]
The signature values are base64 of the full signature field. So you should be able to unbase64 it then parse it as DER, e.g. using `openssl asn1parse -inform DER`
