### ISSUE TITLE
Adding certificates to a x509.CertPool gets increasingly slow

### ISSUE THREAD

**Issue by dadrian** [zmap/zcrypto#73]
We should investigate if there's a clear way to speed this up. This becomes visible as you add more than 10-20K certificates to a single pool.

**Comment by bvandersloot** [comment]
@umbernhard has resolved this for the go x509 during cert perspectives.

**Comment by umbernhard** [comment]
"resolved" is a generous term. https://github.com/zmap/zgrab/commit/1696775450abd2c1213f7f6e424a328e3b2d0b6a

**Comment by umbernhard** [comment]
For cert perspectives we were guaranteed that we were only ever adding unique certs, so there was no need to search for duplicates (which is where the quadratic comes from)

**Comment by umbernhard** [comment]
Also, it seems like in the overwhelming majority of cases, certs don't get duplicated, so the check is guaranteed to always be worst case. Might be better to add all certs and then check for duplicates every once in a while (unless that messes up the database keying or something)

**Comment by dadrian** [comment]
Resolved by #77
