### ISSUE TITLE
x509.Certificate JSON Marshalling does not use best practices

### ISSUE THREAD

**Issue by dadrian** [zmap/zcrypto#78]
The implementation of `MarshalJSON` for x509.Certificate seems to have been written before we knew about `omitempty`. We need to go through and clean up the implementation in several ways:

1. Composed types should mostly have their own `MarshalJSON` functions implemented, instead of doing the whole thing top down with private structs.
2. Key marshaling is very inconsistent. We have some help from `zgrab/ztools/keys` with this. We should probably instead define these Marshalers somewhere in ZCrypto, and use them within ZCrypto and ZGrab as needed.
3. We should not use a `map[string]interface{}` anywhere.
4. We should ensure we have Unmarshalers for anything that has a Marshaler.
5. We should write tests for the Marshalers and Unmarshalers.

We may want to consider breaking this issue down into several subissues, but I think this provides a decent overview of the problem. Effectively, `x509/json.go` needs a large rewrite/refactor.

**Comment by casebenton** [comment]
Breaking this into smaller issues. Resolutions for each item from the list above:

1. Filed #170.
2. Filed  #168
3. Filed #167
4. Filed #169
5. Filed #160 (complete) 

This issue is effectively resolved once we close the issues listed above.

**Comment by casebenton** [comment]
All sub-issues are now complete, so this issue is fully complete.
